name: uthm_smart_campus
description: UTHM Smart Campus Companion - University student services app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.20.2

  # Google Maps
  google_maps_flutter: ^2.5.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  flutter_timezone: ^5.0.2
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.5
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
